<?php
/**
 * @file
 * Install, update, and uninstall functions for the portal module.
 */

/**
 * Upgrade from Drupal 7.
 */
function portal_update_1000() {
  // Convert D7 variables to config.
  $config = config('portal.settings');
  $config->set('opinion_of_backdrop', update_variable_get('portal_opinion_drupal', 'Awesome!'));
  $config->save();

  // Delete D7 variables.
  update_variable_del('portal_opinion_drupal');
}
