<?php
/**
 * @file
 * A short description of this module.
 */

/**
 * Implements hook_config_info().
 */
function portal_config_info() {
  return array(
    'portal.settings' => array(
      'label' => t('portal settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function portal_menu() {
  return array(
    'admin/config/system/portal' => array(
      'title' => 'portal',
      'description' => 'Configure portal.',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('portal_configuration_form'),
      'access arguments' => array('administer portal'),
      'file' => 'portal.admin.inc',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function portal_permission() {
  return array(
    'administer portal' => array(
      'title' => t('Administer portal'),
    ),
  );
}


/**
 * Implements hook_entity_info().
 */
function portal_entity_info() {

  $info = array();

  $info['portal'] = array(
    'label' => t('Portal'),
    'base table' => 'portal_group',
    'entity keys' => array(
      'id' => 'portal_gid',
      'label' => 'Portal Group',
    ),
    'module' => 'portal',
  );

  return $info;
}
